odpf/optimus

integration_tests/compiler_test.go, integration_tests/expected_compiled_template.py, models/hook.go, models/task.go, plugin/gen.go, resources/pack/templates/scheduler/airflow_1/base_dag.py
- Passing `main.Version` as the binary flag during compilation to avoid updating manually inside the code.
=> fix: remove unwanted workdir set in docker template for plugins

cmd/opctl/main.go, cmd/optimus/main.go, ext/scheduler/airflow/tests/requirements.txt, ext/scheduler/airflow2/airflow.go, ext/scheduler/airflow2/airflow_test.go, ext/scheduler/airflow2/tests/.gitignore, ext/scheduler/airflow2/tests/Makefile, ext/scheduler/airflow2/tests/README.md, ext/scheduler/airflow2/tests/requirements.txt, ext/scheduler/airflow2/tests/test_compiled_airflow_template.py, ext/scheduler/airflow2/tests/test_cross_tenant_dep_sensor.py, integration_tests/airflow_1/compiler_test.go, integration_tests/airflow_1/expected_compiled_template.py, integration_tests/airflow_1/integration_tests.go, integration_tests/airflow_2/compiler_test.go, integration_tests/airflow_2/expected_compiled_template.py, integration_tests/airflow_2/integration_tests.go, resources/pack/templates/scheduler/airflow_1/base_dag.py, resources/pack/templates/scheduler/airflow_2/__lib.py, resources/pack/templates/scheduler/airflow_2/base_dag.py
- Scheduler to use Airflow 2 resources
- Change env_vars to follow Airflow 2 model
- Use SlackAPIPostOperator to handle alerts
- Use Airflow 2 stable API instead of experimental & adjust the response.
- Replace deprecated dependencies
- Remove unused imports
=> feat: add & use airflow 2 scheduler

api/handler/v1/runtime.go, docs/concepts/architecture.md, job/service.go, plugin/hook/connector.go, plugin/task/connector.go, store/gcs/job_repository.go
Fixed broken architecture diagram link.
=> refactor: task/hook plugins server should have constructor

api/handler/v1/runtime.go, ext/scheduler/airflow/airflow.go, ext/scheduler/airflow/resources/__lib.py, ext/scheduler/airflow2/airflow.go, ext/scheduler/airflow2/airflow_test.go, ext/scheduler/airflow2/resources/__lib.py, models/project.go
Signed-off-by: Kush Sharma <thekushsharma@gmail.com>
=> fix: cross entity sensor should use updated job metadata api

store/postgres/resource_spec_repository.go
This helps track YAML parsing errors
=> refactor: pass raw resource with spec yaml parsing errors

.github/workflows/integration-test.yml, Makefile, store/postgres/job_spec_repository_test.go
=> refactor: automate postgres through github worklows

api/handler/v1/runtime.go, api/handler/v1/runtime_test.go, cmd/replay.go, cmd/server/server.go, ext/third_party/OpenAPI/odpf/optimus/runtime_service.swagger.json, job/replay.go, job/replay_manager.go, job/replay_manager_test.go, job/replay_test.go, job/service.go, mock/job.go, mock/replay.go, models/job.go, store/postgres/replay_repository.go, store/postgres/replay_repository_test.go, store/store.go
Add replay list sub command to get list of recent replays per project.
**Usage:**
optimus replay list --project [project_name]
=> feat: add replay list sub command

docs/docs/concepts/overview.md, docs/docs/guides/replay.md, docs/sidebars.js
Added documentation on how to use replay feature and the concept of replay. Will add more doc on this part after added backup in replay.
=> docs: add replay guide & concept

cmd/admin_build_instance.go, cmd/backup.go, cmd/commands.go, cmd/deploy.go, cmd/job.go, cmd/replay.go, cmd/resource.go, cmd/serve.go, go.mod, go.sum
- Add a grouping of CLI commands to the core and additional groups.
=> feat(cli): add command grouping

ext/scheduler/airflow/resources/__lib.py, ext/scheduler/airflow2/resources/__lib.py
ref : https://github.com/odpf/optimus/issues/139
=> feat: Print Basic Details of Task Image Version 

ext/scheduler/airflow/resources/base_dag.py, ext/scheduler/airflow/resources/expected_compiled_template.py, ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
maintain only OPTIMUS_HOST variable across plugins and airflow dags
=> fix : maintain single optimus host variable across environment

.github/workflows/lint.yml, .golangci.yml, Makefile
We can enable other linters after the issues with them are resolved.
=> Enable all linters, disable only the problamatic ones

.github/workflows/test.yml, Makefile, store/postgres/backup_repository_test.go, store/postgres/instance_repository_test.go, store/postgres/job_spec_repository_test.go, store/postgres/jobrun_repository_test.go, store/postgres/namespace_repository_test.go, store/postgres/project_repository_test.go, store/postgres/replay_repository_test.go, store/postgres/resource_spec_repository_test.go, store/postgres/secret_repository_test.go
* will run unit test only once
* integration test ran all test, will not only run store path
* Integration test setup based on:
https://www.gojek.io/blog/golang-integration-testing-made-easy
=> refactor: change command for running test in makefile

cmd/version.go
closes https://github.com/odpf/optimus/issues/171
=> fix: use of progress on version call

cmd/backup_create.go, cmd/job_create.go, cmd/job_hook.go, cmd/job_render.go, cmd/namespace.go, cmd/resource.go
optimus falls into a infinite loop while asking to select for nameSpaces if nameSpaces are empty in the config file
=> fix: handle empty nameSpaces config to prevent infinite prompt loop

config/loader_test.go, go.mod, go.sum
=> fix: when file config not exist return error

cmd/admin.go, cmd/admin_build_instance.go, cmd/backup.go, cmd/backup_create.go, cmd/backup_list.go, cmd/backup_status.go, cmd/job.go, cmd/job_create.go, cmd/job_hook.go, cmd/job_render.go, cmd/job_run.go, cmd/job_run_list.go, cmd/job_validate.go, cmd/replay.go, cmd/replay_create.go, cmd/replay_list.go, cmd/replay_status.go, cmd/resource.go, cmd/secret.go
=> fix: prerun client config load

cmd/deploy.go, models/job.go, store/local/job_spec_repository.go, store/local/job_spec_repository_test.go
This PR is to address issue #275 .
* log error when deploying resource, just like for the job
* catch empty resource error for a certain namespace
=> Fix Minor Bug on Log and Error catching

cmd/admin_build_instance.go, cmd/backup_create.go, cmd/backup_list.go, cmd/backup_status.go, cmd/commands.go, cmd/connectivity.go, cmd/deploy.go, cmd/job_create.go, cmd/job_refresh.go, cmd/job_run.go, cmd/job_run_list.go, cmd/job_validate.go, cmd/namespace.go, cmd/project.go, cmd/replay_create.go, cmd/replay_list.go, cmd/replay_status.go, cmd/resource.go, cmd/secret.go, cmd/version.go
This PR is to address the need to refactor `deploy` command.
To merge this PR, the following should be confirmed:
=> Refactor deploy

cmd/server/optimus.go, cmd/server/scheduler.go, config.sample.yaml, config/config_server.go, config/loader_test.go, ext/scheduler/airflow2/airflow.go, ext/scheduler/airflow2/airflow_test.go, ext/scheduler/prime/scheduler.go, models/scheduler.go
=> fix: deploy lib.py along with deploy job specs

ext/scheduler/airflow2/resources/__lib.py
currently sensor fails incase of upstream hasn't started
=> fix: sensor shouldn't fail in case optimus returns a non 200 response.

cmd/job/refresh.go, job/deploy_manager.go
1. Add logs of which project is currently being deployed and how long it has been started.
2. Add logs of which deployment is being canceled due to time out.
3. Remove unnecessary sprintf in job refresh CLI.
4. Treat job refresh stream EOF response as an error, as it should be unexpected. The expected EOF that Job Refresh expecting is when it receives the job deployment ID.
=> fix: add missing logs on job deployment and fix job refresh cli

api/handler/v1beta1/observer.go, api/handler/v1beta1/observer_test.go, api/handler/v1beta1/resource.go, datastore/service.go, datastore/service_test.go, models/datastore.go, models/datastore_test.go
This PR is to address #342 .
Changes:
* updated the implementation in service layer
* rework unit tests for the impacted methods
=> feat: resource apply changes only if different

job/service.go, job/service_test.go
closing https://github.com/odpf/optimus/issues/458
=> fix: bug unable to deploy job without dependency mod

job/dependency_resolver_test.go, store/postgres/adapter.go, store/postgres/job_spec_repository.go, store/postgres/job_spec_repository_test.go
resolving https://github.com/odpf/optimus/issues/465
=> fix: bug external sensor created when internal sensor with same urn exist

Makefile
updating proton commit in Makefile with this change in proton: https://github.com/odpf/proton/pull/158
=> chore: update proton commit of adding unknown_dependencies field

cmd/deploy/deploy.go
Resolving https://github.com/odpf/optimus/issues/484.
=> fix: bug job deployment failed and cancelled not returning error

docs/docs/concepts/overview.md
Add external optimus server dependency in the dependency resolver concept.
=> docs: add job dependency to cross optimus server in concept

ext/scheduler/airflow2/compiler/compiler_test.go, ext/scheduler/airflow2/compiler_test.go, ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
Resolving https://github.com/odpf/optimus/issues/487
=> fix: set depends on past value set by users in transformation task level

ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
* fix: set publish_job_end_event trigger to 'all_success'
=> fix: `job_end_event` trigger set to  `all_success` (#510)

cmd/admin/build_instance.go, cmd/backup/create.go, cmd/backup/list.go, cmd/backup/status.go, cmd/commands.go, cmd/deploy/deploy.go, cmd/extension/clean.go, cmd/extension/uninstall.go, cmd/internal/logger/color.go, cmd/internal/logger/logger.go, cmd/internal/logger/printer.go, cmd/internal/survey/backup_create.go, cmd/internal/survey/replay_create.go, cmd/job/refresh.go, cmd/job/run.go, cmd/job/run_input.go, cmd/job/validate.go, cmd/replay/create.go, cmd/replay/list.go, cmd/replay/status.go, cmd/secret/delete.go, cmd/secret/list.go, cmd/secret/set.go, cmd/version/version.go, go.mod, server/optimus.go
refactored the logger , changed the formatter to add colours for the logger , modified the subsequent log statements accordingly
=> fix:refactored logger

store/postgres/job_spec_repository.go, store/postgres/job_spec_repository_test.go
fixing https://github.com/odpf/optimus/issues/544
=> fix: get static dependency issue that points to other external project jobs with same job name

api/handler/v1beta1/adapter.go, cmd/backup/create.go, cmd/job/addhook.go, cmd/job/create.go, cmd/job/render.go, cmd/job/validate.go, config/loader.go, server/optimus.go, server/scheduler.go, store/postgres/postgres.go, store/postgres/postgres_test.go, tests/setup/database.go
Tracker can be seen here https://github.com/odpf/optimus/issues/545
=> refactor: cleanup minor part 1

ext/notify/slack/slack.go, ext/notify/slack/slack_test.go, job/event.go, models/job.go
* fix: handle multiple job failure error types
* fix: handle lint issues for  workerErrChan in slack_test
=> Fix: handle job failure event msg block builder (#582) (cherry pick commit form release 0.3)

ext/scheduler/airflow2/airflow.go, ext/scheduler/airflow2/airflow_test.go, ext/scheduler/prime/scheduler.go, job/deployer.go, job/deployer_test.go, job/service.go, job/service_test.go, mock/scheduler.go, models/scheduler.go
* fix : handle deletions for both namespace id vs namespace name folders
* fix: test cases fix for job deleteion bug on namespace directory name change
* fix: delete old namespace folder if empty after the delete api too
* fix: dont expose dag dir deletion code
=> fix : handle deletions for both namespace id vs namespace name folders

internal/store/postgres/record_test.go
This PR is to address the reduced coverage report as part of [this PR](https://github.com/odpf/optimus/pull/607).
=> test: add tag on unit test to fix coverage report

client/local/internal/internal.go, client/local/specio/job_spec_io.go, client/local/specio/job_spec_io_test.go
=> fix: spec reading where asset is optional

dev/Makefile, dev/README.md, dev/airflow.values.yaml, dev/optimus.values.yaml, dev/postgres.yaml, dev/pvc.yaml
* support for only mac
* uses colima for local k8s
* helm charts used: airflow and optimus
* dags folder at `/tmp/colima/dags`
* plugin can also be mounted (refer `dev/README.md`)
* depends on https://github.com/odpf/charts/pull/79
=> feat : add dev setup

Makefile, internal/errors/errors.go, internal/errors/multi.go, internal/errors/multi_test.go, internal/store/postgres/tenant/namespace_repository_test.go, server/logger.go, server/optimus.go
This PR is to add or update the existing implementations for the need of bounded context refactor, such as resource and job. The implementations under this PR are partly being fetched from another commit:
* log wrapper https://github.com/odpf/optimus/pull/650/commits/55b2fb6e29df76fc0d1216f6f9e847a28af21de3
* multi-error https://github.com/odpf/optimus/pull/650/commits/fc026b5efde587ad6d8ff18bad8f78e471d11611 https://github.com/odpf/optimus/pull/650/commits/9fdbbb0df871c86677b1e05b5d83710fc726dea6
* repository test https://github.com/odpf/optimus/pull/650/commits/3615d9a82c09a71ebb24f5d244cd8e05f8309712
* complete error https://github.com/odpf/optimus/pull/650/commits/35003ed22c61badce9d09b9ecc82f1fb0a5cb8cb
=> feat: add bounded context utility

job/replay_test.go, job/service.go, job/service_test.go
=> fix: replay fix dependency resolution

Dockerfile, entrypoint_init_container.sh, ext/scheduler/airflow2/resources/__lib.py, ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py, plugin/yaml/plugin.go, plugin/yaml/tests/sample_plugin.yaml
Changes :
* init-container:
* airflow deploys -  init container + executor container
* `fetches config` : airflow to load config onto init-container & executor container
* default_env + fetched_env in airflow
* `fetches assets` : init container to load assets onto shared volume
* `job run-input` api : to compile + fetch assets; instead of admin build instance
=> feat : simplify plugin ecosystem (init-container)

.github/workflows/publish-latest.yml
`Issue` : building optimus executable in ubuntu and using it in  alpine docker image.
`Fix` : set `CGO_ENABLED=0`
References:
- https://www.reddit.com/r/golang/comments/pi97sp/comment/hboi9h4/?utm_source=share&utm_medium=web2x&context=3
- https://jvns.ca/blog/2021/11/17/debugging-a-weird--file-not-found--error/
=> fix : avoid dynamically linked executable in latest builds

ext/scheduler/airflow/__lib.py
This PR is similar to the previous PR [here](https://github.com/odpf/optimus/pull/693). The difference is, this PR is intended for the main branch after it was merged with the redesign.
=> fix: bug in __lib.py

go.mod, go.sum, main.go
Adjusting parameter for kubernetes.
Ref: https://blog.devgenius.io/know-gomaxprocs-before-deploying-your-go-app-to-kubernetes-7a458fb63af1
=> chore: adjust GOMAXPROCS for kuberenetes

client/cmd/job/refresh.go, client/cmd/job/replace_all.go, client/cmd/resource/upload_all.go
Co-authored-by: Sandeep Bhardwaj <sandeep.bhardwaj@gojek.com>
=> fix: increase timeouts for long running operations

client/cmd/deploy/deploy.go, client/cmd/job/refresh.go
Co-authored-by: Sandeep Bhardwaj <sandeep.bhardwaj@gojek.com>
=> fix: update deploy timeout to 60 minutes as in few situations it is crossing 30 minutes

ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
Changes for removing job start event and job end event in airflow dag for v0.5.8
=> fix: job_start_event and job_end_event removed from dag templates
