api/proto/odpf/optimus/hook_plugin_grpc.pb.go, api/proto/odpf/optimus/runtime_service_grpc.pb.go, api/proto/odpf/optimus/task_plugin_grpc.pb.go, docs/developer/write-a-plugin.md, docs/tables.md, integration_tests/airflow_1/compiler_test.go, integration_tests/airflow_1/expected_compiled_template.py, integration_tests/expected_compiled_template.py, plugin/gen.go, resources/pack/templates/scheduler/airflow_1/base_dag.py, resources/pack/templates/scheduler/airflow_2/base_dag.py, third_party/OpenAPI/odpf/optimus/runtime_service.swagger.json
During an instance execution, there a few variables getting injected inside the container, two of which are `TASK_TYPE` and `TASK_NAME`, both of them should be renamed to use `INSTANCE_` as a prefix to be more generic.
- docs: how to write a task plugin
- refactor: remove unwanted `GOOGLE_APPLICATION_CREDENTIALS` env
=> refactor: using INSTANCE_ prefix instead of TASK_ in container env

api/handler/v1/runtime.go, cmd/commands.go, cmd/create.go, cmd/deploy.go, cmd/render.go, cmd/server/server.go, cmd/validate.go, cmd/version.go, ext/datastore/bigquery/table_spec.go, go.mod, go.sum, job/job.go, job/service.go, main.go, mock/job.go, store/local/job_spec_repository.go, store/local/job_spec_repository_test.go, store/local/resource_spec_repository.go, store/local/resource_spec_repository_test.go, store/postgres/instance_repository_test.go, store/postgres/job_spec_repository.go, store/postgres/job_spec_repository_test.go, store/postgres/project_repository.go, store/store.go, utils/contains.go, utils/contains_test.go
Users should be able to select directories when a new job or resource is created. Adding a new question to CLI that will ask directories(and sub directories if needed) to find where exactly the spec should be created instead of creating them at the root all the time.
=> feat(cli): ask for directories from user before creating new specification

docs/docs/reference/shell-autocompletion.md
1.  Automatically adds completion command for [shell completions](https://github.com/spf13/cobra/blob/master/shell_completions.md) for bash, zsh, fish and PowerShell. 
2. Users can configure the command auto creation:  
1. disable the creation of the completion command
2. disable completion descriptions
3. disable the --no-descriptions flag for "always on" completion descriptions
**Command to use : `./optimus [tab][tab]`**
Issue #32
=> docs: add the shell-autocompletion support in optimus cli

cmd/version.go, go.mod, go.sum
If the user wants to check whether any latest binary release is available (it can be minor release too).
**Just need to trigger the command to check the released update : `optimus version`**
Issue #27
=> feat: support latest binary alert feature through cli 

docs/docs/guides/create-bigquery-external-table.md, docs/sidebars.js
Create documentation for bigquery external table resource addressed in this closed issue: https://github.com/odpf/optimus/issues/44
=> docs: add documentation for bigquery external table resource

cmd/server/server.go, docs/docs/concepts/overview.md, job/dependency_resolver.go, job/dependency_resolver_test.go, job/replay_test.go, job/service.go, job/service_test.go, mock/job.go, store/postgres/job_spec_repository.go, store/postgres/job_spec_repository_test.go, store/store.go
Support for cross-project static inter dependencies in job.
```yaml
#
#
dependencies:
- job: sample_internal_job
type: intra
- # inter dependencies should prefix job name with project name divided by
job: cross_project/sample_external_job
type: inter
```
=> feat: support static inter project dependencies

ext/scheduler/airflow/airflow.go, ext/scheduler/airflow/airflow_test.go, ext/scheduler/airflow2/airflow.go, ext/scheduler/airflow2/airflow_test.go, job/replay_manager_test.go
- only list jobs for airflow that belong to that namespace
- turn off failing replay test temporarily
=> refactor: optimise list jobs operation for airflow

job/dependency_resolver.go, job/dependency_resolver_test.go, job/service.go, job/service_test.go, mock/job.go, store/postgres/job_spec_repository.go, store/postgres/job_spec_repository_test.go, store/store.go
https://github.com/odpf/optimus/issues/89
if during dependency resolution, multiple jobs have same destination it should give higher priority to select a job that belongs to the same project first, then choose anyone from the rest if not found.
=> fix: dependency resolution during duplicate destinations of job

.optimus.sample.yaml, docs/docs/getting-started/configuration.md
As part of supporting multiple namespaces in a project, there were breaking changes in the Optimus project configuration.
=> docs: modify optimus configuration sample

ext/scheduler/airflow/resources/base_dag.py, ext/scheduler/airflow/resources/expected_compiled_template.py, ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
Add dagrun_timeout to prevent having unnecessary slot-consuming long-running dagruns.
The default value is set to 3 days, however, it can be set through this Airflow variable `dagrun_timeout_in_secs`.
=> feat: add dagrun_timeout to airflow dag

ext/scheduler/airflow2/resources/__lib.py
fix: set CrossTenantDependancySensor mode from default poke to reschedule
Issue Link: https://github.com/odpf/optimus/issues/144
=> fix: set CrossTenantDependancySensor mode from poke to reschedule

docs/docs/rfcs/20220216_improving_time_and_flow_of_deployment.md
RFC to improve the time taken to do:
* Job deployment
* Job creation
* Job deletion
* Replay
* Backup
=> docs(rfc): Improve Time & Flow of the core Job Deployment & other areas

api/handler/v1beta1/job_spec.go, api/handler/v1beta1/resource.go, cmd/deploy.go
This PR addresses:
* bug when namespaces are not configured, meaning missing namespace when deployment
* missing logging on job and resource deployment from the Optimus client
Log Before this PR:
```zsh
> [namespac1] Deploying resources for bigquery
> [namespace2] Deploying resources for bigquery
> [namespace1] Deploying jobs
> [namespace2] Deploying jobs
```
Log After this PR:
```zsh
> Deploying bigquery resources for namespace [namespace1]
> Deploying bigquery resources for namespace [namespace2]
> Receiving responses:
[1/2] resource1 successfully deployed
resources with namespace [namespace1] are deployed successfully
[2/2] resource2 successfully deployed
resources with namespace [namespace2] are deployed successfully
> Deploying jobs for namespace [namespace1]
> Deploying jobs for …
```
=> fix: logging for job and resource deployment

cmd/admin.go, cmd/admin_build_instance.go, cmd/backup.go, cmd/backup_list.go, cmd/backup_status.go, cmd/commands.go, cmd/config.go, cmd/deploy.go, cmd/job.go, cmd/job_run_list.go, cmd/replay.go, cmd/replay_create.go, cmd/replay_list.go, cmd/replay_status.go, cmd/resource.go, cmd/secret.go, cmd/serve.go, cmd/version.go, config/loader.go, config/loader_test.go
TODO next (can be done in separate PR):
=> feat: bind config with cobra flags to override the conf

cmd/server/optimus.go, job/deployer.go, job/deployer_test.go, models/job.go, models/job_test.go
Currently, when doing deploy jobs from the Refresh command, the deployment will fail due to the secrets are not found. This is caused by the NamespaceSpec that being passed to the DeployJobs process does not have secrets. 
The workaround is, that instead of NamespaceSpec that being passed is from one of the JobSpec, it will be re-fetched from NamespaceService, which will also include the secrets. This is preferable instead of preloading the secrets 1 by 1 when getting all the jobs.
=> fix: pass namespace spec that has secrets to DeployJobs process

store/postgres/migrations/000020_add_job_dependencies_table.down.sql
Migration 000020 down was wrongly set. It should drop the `job_dependency` table, not drop `job_dependency` field in the `job` table.
Note: `job_dependency` in `job` is not exist.
=> fix: use correct script to drop job_dependency on migration down

cmd/job_create.go, compiler/job_run_input_compiler_test.go
Currently, the catch-up configuration in the job spec is set to `true`. This can be consuming lots of scheduler slots and resources as it will try to run the job from the start date to the current date. The default should be `false`.
=> fix: change catchup default value from true to false

store/postgres/migrations/000021_update_index_on_namespace_table.down.sql, store/postgres/migrations/000021_update_index_on_namespace_table.up.sql
The current version adds index on job table and not namespace: https://github.com/odpf/optimus/blob/main/store/postgres/migrations/000008_add_namespace.up.sql#L13
=> fix: fix index on namespace table

store/postgres/secret_repository.go
This PR is to address a bug when we want to set a secret, where previously it's already deleted. Steps taken to encounter this error:
1. set secret with command `secret set [name] ...`
2. delete the secret with command `secret delete [name]`
3. re-run step 1. above and error should be encountered
The changes in this PR is to just add `Unscoped()` call function (reference)[https://gorm.io/docs/delete.html#Delete-permanently] during deletion to make Optimus delete it permanently.
=> fix: bug when deleting secret

store/postgres/job_dependency_repository.go, store/postgres/job_dependency_repository_test.go
Fixing a compilation [issue](https://github.com/odpf/optimus/issues/348) on Job Refresh. This is caused by the dependency project is not properly loaded, causing the job spec of dependency jobs are not properly loaded.
=> fix: resolve bug when refreshing jobs with cross project dependency

api/handler/v1beta1/adapter.go, api/handler/v1beta1/adapter_test.go, cmd/server/server.go, mock/datastore.go
This PR is to address #352 . Even though the issue only mentioned about resource creation, but this solution should also address the same for updating resource. This is because the update process is similar to the creation.
The followings are the changes done:
* update adapter to add further validation
* create the unit test to address such implementation
* update mock implementation to address the requirement
Based on this PR, there are some TODO that can be addressed through **separate cards**, as the changes might be bigger.
* add validation on the adapter initialization
* add more unit test on the adapter to address more cases
* update mock implementation to address two points above
* finding out the similar case where the server could crash based on the request from the user
=> fix: server crash when accepting improper resource create request

config/loader.go, config/loader_test.go
Latest version of salt returns error when config file is not exist, meanwhile, in optimus, when config file is not exist, optimus can load the config via env var
=> fix: load server config from env var

ext/resourcemgr/model.go, ext/resourcemgr/optimus.go, ext/resourcemgr/optimus_test.go
resolving https://github.com/odpf/optimus/issues/477
=> fix: bug unable to decode GetJobSpecificationsResponse for jobs with hook

job/dependency_resolver.go, job/external_dependency_resolver.go, job/external_dependency_resolver_test.go
* refactor: change external optimus sensor task id similar with internal sensor task id (#491)
* refactor: change external optimus sensor task name similar with internal sensor name
* fix: cross optimus task dependencies in airflow is not properly
* refactor: revert cross optimus sensor variable name
Co-authored-by: Anwar Hidayat <anwarhidayat14@gmail.com>
* fix: bug caused by error when getting dependencies from external resource manager
* fix: bug on unknown dependencies being updated
Co-authored-by: Arinda Arif <79823430+arinda-arif@users.noreply.github.com>
=> fix: bug breaking deploy on resource manager failure (#500)

ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
with trigger as `all_done` even after task failure , the job_end_event shall run successfully, marking the job run state as successful, 
setting the trigger to `all_success` we can avoid that situation.
=> fix: `job_end_event` trigger set to  `all_success`

store/postgres/migrations/000028_job_run_delete_cascade.down.sql, store/postgres/migrations/000028_job_run_delete_cascade.up.sql
fixes :  [551](https://github.com/odpf/optimus/tree/551-bug-unable-to-recreate-deleted-jobs-with-same-name)
=> fix: delete cascade job_run and task, sensor, hook runs

cmd/version/version.go, models/plugin.go, models/plugin_test.go, plugin/plugin.go, plugin/yaml/plugin.go, plugin/yaml/plugin_test.go
changes:
* load yaml and binary plugins if available
* revert plugin discovery logic to dynamic to accommodate discover existing binary plugins  at client end
Now, Plugin struct can contain multiple implementations (yaml, bin)
and use-cases can choose what ever implementations as per requirements.
Plugin instances can exists as follows:
1. Binary imp. only
2. Binary & Yaml Impl.
3. Yaml Impl. only
=> fix : backward compatibility in loading yaml plugins

Dockerfile
The user in Optimus Dockerfile when configured/overridden to be non-root user will cause file permission issue as default user in alpine is root.
In order to support plugin installation on server boot, default non-root user is added to Dockerfile.
=> fix : add non-root user in docker file

Dockerfile, entrypoint_init_container.sh
Command job run-input will fail if the task instance before `job_start_event` feat introduced is triggered. It happens because the old instance is not registered in the `job_run` table yet. So we need to register the instance either using `admin build instance` or manually trigger `job_start_event`.
In this implementation, fail to run command `job run-input` will fallback to `admin build instance`
=> feat: call job run input to compile + fetch assets

plugin/plugin.go
to maintain backward compatibility, add missing usr/bin and usr/local/bin paths in plugin discovery
=> fix : add missing usr/bin into plugin discover path

client/cmd/job/validate.go, client/local/model/job_spec.go
The bugs that are being fixed here:
* bug on `optimus job validate` command, in which the parent is not merged to the actual job
* bug when merging parent and actual job (applicable to the related commands) caused by lack of checking
=> fix: job and parent merge on job load

core/job/job.go, core/job/job_test.go, core/job/resolver/external_upstream_resolver.go, core/job/resolver/external_upstream_resolver_test.go, core/job/service/job_service.go, core/job/service/job_service_test.go, internal/store/postgres/job/adapter.go, internal/store/postgres/job/job_repository.go, internal/store/postgres/job/job_repository_test.go
=> fix: job bounded context issues

ext/scheduler/airflow2/resources/__lib.py
This PR is to address bug in `__lib.py` file. This causes job to fail if execution meet the criteria. The following is the error message if this bug is encountered:
```zsh
ValueError: too many values to unpack (expected 2)
```
=> fix: bug in __lib.py

ext/scheduler/airflow/__lib.py
**Is your feature request related to a problem? Please describe.**
The existing sensor metric "sensor_start_event" call back gets invoked on every sensor poke.
This results in redundant database calls on optimus server. To overcome this we need to have some sort of stateful storage that can limit the "sensor_start_event" to only once per sensor attempt. 
**Describe the solution you'd like**
It's ideal to use the XCOMs as a state storage for maintaining the record of events pushed per sensor attempt. 
Before pushing the event to optimus the scheduler can check if a start event has already been sent 
**Describe alternatives you've considered**
1. Reading the state of job run from the optimus server itself
2. keeping a cache at optimus
=> fix: only send sensor start event on first poke

core/job/handler/v1beta1/job.go, core/job/handler/v1beta1/job_test.go, core/job/resolver/internal_upstream_resolver.go, core/job/resolver/internal_upstream_resolver_test.go, core/job/service/job_service.go, core/job/service/job_service_test.go, internal/store/postgres/job/adapter.go, internal/store/postgres/job/job_repository.go, internal/store/postgres/job/job_repository_test.go, internal/store/postgres/scheduler/job_repository.go
1. `upstream_job_id` in `job_upstream` table is always empty, causing any deletion in `job` table will not automatically deleting the entries in `job_upstream` table.
2. failure when resolving static dependency when **inspecting** a non-existing job which does not have static upstream specified.
3. summarize replace all error messages (all namespaces) in the end of the process.
4. failure when job is not found when inspecting.
5. unclear upstream job not found log when inspecting.
=> fix: empty upstream job id issue and dependency resolution on job inspect issue

core/job/handler/v1beta1/job.go, core/job/resolver/external_upstream_resolver.go, core/job/resolver/external_upstream_resolver_test.go, core/job/service/job_service.go
- Skip the external upstream resolver (bulk) process when external resource manager is not found.
- Add more server logs on job bounded context
- Add replace all, refresh, and validation duration metrics
=> fix: avoid unnecessary upstream resolver process and improve server logs

client/cmd/plugin/validate.go, ext/scheduler/airflow/__lib.py, ext/scheduler/airflow/dag/compiler_test.go, ext/scheduler/airflow/dag/dag.py.tmpl, ext/scheduler/airflow/dag/expected_dag.py, ext/scheduler/airflow/dag/models.go, internal/models/plugin.go, plugin/yaml/plugin.go, plugin/yaml/plugin_test.go, plugin/yaml/tests/sample_plugin.yaml, plugin/yaml/tests/sample_plugin_schema_invalid.yaml, plugin/yaml/tests/sample_plugin_without_version.yaml, sdk/plugin/mock/plugin.go, sdk/plugin/plugin.go, sdk/plugin/plugin_test.go
=> feat: configurable endpoint for kubernetes pod executor

ext/scheduler/airflow2/resources/base_dag.py, ext/scheduler/airflow2/resources/expected_compiled_template.py
`depends_on_past` value in job level configuration (not task), should also be overrideable from the user's configuration to avoid having a dag in a deadlock state (when scheduler schedules run in a random run order).
=> fix: override depends_on_past's dag level value
